---
all:
  children:
    ansible_controller:
      hosts:
        localhost:
          ansible_connection: local
    windows_dns:
      hosts:
        addc.poc.local:
          ansible_host: 10.23.22.100
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_port: 5985
          ansible_winrm_server_cert_validation: ignore
          ansible_user: "{{ vault_ad_username }}"
          ansible_password: "{{ vault_ad_password }}"
