#!/usr/bin/env bash
set -euo pipefail

# Install/provide nmstatectl on Ubuntu 24.04.x for OpenShift Agent ISO static-network generation.
#
# RHEL/Rocky/Fedora provide nmstatectl via the nmstate package. Ubuntu 24.04/Noble
# often does not. The Python nmstate package from PyPI is also awkward on Noble
# because it pulls PyGObject/nispor dependencies that are not consistently
# available as wheels/packages.
#
# This helper therefore does the following:
#   1. uses a native apt nmstatectl if Ubuntu provides one
#   2. tries the Python nmstate CLI if already working
#   3. otherwise installs a small nmstatectl-compatible shim for the specific
#      OpenShift Agent Installer use case: `nmstatectl gc <state-file>`.
#
# The shim supports the simple static ethernet config generated by this repo for
# SNO on VMware. For bonds/VLANs/bridges, use a RHEL/Rocky bastion with the real
# nmstate package.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${VENV_DIR:-${REPO_ROOT}/.venv}"
SYSTEM_DIST_PACKAGES="${SYSTEM_DIST_PACKAGES:-/usr/lib/python3/dist-packages}"
USE_SHIM="${USE_NMSTATECTL_AGENT_SHIM:-true}"

if ! grep -q '^ID=ubuntu' /etc/os-release; then
  echo "ERROR: this helper is intended for Ubuntu." >&2
  exit 1
fi

source /etc/os-release
if [[ "${VERSION_ID}" != 24.04* ]]; then
  echo "Warning: detected Ubuntu ${VERSION_ID}; continuing anyway." >&2
fi

if [[ ! -d "${VENV_DIR}" ]]; then
  echo "Creating Python venv at ${VENV_DIR}..."
  python3 -m venv "${VENV_DIR}"
fi

# shellcheck source=/dev/null
source "${VENV_DIR}/bin/activate"

# Prefer a real/native nmstatectl when one exists outside the repo venv.
# IMPORTANT: do not mistake an older .venv/bin/nmstatectl shim for an apt/native
# install.  V8 did exactly that and exited before refreshing the corrected shim.
SYSTEM_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
native_nmstatectl="$(PATH="${SYSTEM_PATH}" command -v nmstatectl 2>/dev/null || true)"
if [[ -n "${native_nmstatectl}" ]]; then
  if "${native_nmstatectl}" --version >/dev/null 2>&1 || "${native_nmstatectl}" -h >/dev/null 2>&1; then
    echo "Native nmstatectl already available: ${native_nmstatectl}"
    # Remove any repo shim that would otherwise shadow the native binary while
    # the venv is activated.
    rm -f "${VENV_DIR}/bin/nmstatectl" "${VENV_DIR}/bin/nmstatectl.agent-shim.py"
    hash -r
    "${native_nmstatectl}" --version || "${native_nmstatectl}" -h | head -1 || true
    exit 0
  fi
fi

echo "Installing Ubuntu runtime packages used by the shim and optional native NMState..."
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ca-certificates \
  curl \
  network-manager \
  python3-venv

# Some Ubuntu mirrors/images may publish nmstate. Try it, but do not rely on it.
echo "Checking for an apt nmstate package..."
if apt-cache show nmstate >/dev/null 2>&1; then
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nmstate || true
fi

# Re-check only the system PATH.  Never check the activated venv here, otherwise
# an old repo shim will be mistaken for the package we just tried to install.
native_nmstatectl="$(PATH="${SYSTEM_PATH}" command -v nmstatectl 2>/dev/null || true)"
if [[ -n "${native_nmstatectl}" ]]; then
  if "${native_nmstatectl}" --version >/dev/null 2>&1 || "${native_nmstatectl}" -h >/dev/null 2>&1; then
    echo "nmstatectl installed natively: ${native_nmstatectl}"
    rm -f "${VENV_DIR}/bin/nmstatectl" "${VENV_DIR}/bin/nmstatectl.agent-shim.py"
    hash -r
    "${native_nmstatectl}" --version || "${native_nmstatectl}" -h | head -1 || true
    exit 0
  fi
fi

# PyYAML is enough for the local shim. Do not attempt to compile PyGObject/nispor.
echo "Installing PyYAML into the repo venv..."
python -m pip install --upgrade pip wheel setuptools
python -m pip install --upgrade 'PyYAML>=6.0'

if [[ "${USE_SHIM}" != "true" ]]; then
  echo "ERROR: native nmstatectl is unavailable and USE_NMSTATECTL_AGENT_SHIM is not true." >&2
  exit 1
fi

echo "Installing OpenShift Agent nmstatectl gc shim for Ubuntu..."
# Remove any stale repo shim before writing the current implementation.
rm -f "${VENV_DIR}/bin/nmstatectl" "${VENV_DIR}/bin/nmstatectl.agent-shim.py"

cat > "${VENV_DIR}/bin/nmstatectl.agent-shim.py" <<'PY'
#!/usr/bin/env python3
import json
import os
import sys
import uuid
import ipaddress
from typing import Any, Dict, List, Optional

try:
    import yaml
except Exception as exc:
    print(f"nmstatectl agent shim requires PyYAML: {exc}", file=sys.stderr)
    sys.exit(2)

VERSION = "Nmstate version: agent-shim-for-openshift-agent-ubuntu-v9"


def usage() -> None:
    print("nmstatectl agent shim")
    print("Supported commands: --version, -h, help, gc <network-state-yaml-or-json>")


def load_state(args: List[str]) -> Dict[str, Any]:
    # Real nmstatectl gc accepts a file path. Assisted-service may pass a temp file
    # or stdin. Support both, plus '-' for stdin.
    input_data = ""
    file_args = [a for a in args if not a.startswith("-") and a not in {"gc", "genconf", "generate-config"}]
    path = file_args[-1] if file_args else "-"

    if path == "-":
        input_data = sys.stdin.read()
    elif os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            input_data = f.read()
    else:
        # Some callers pass the YAML/JSON as an argument rather than as a file.
        input_data = path

    if not input_data.strip():
        raise ValueError("empty network state provided")

    try:
        state = json.loads(input_data)
    except Exception:
        state = yaml.safe_load(input_data)

    if not isinstance(state, dict):
        raise ValueError("network state must be a YAML/JSON object")
    return state


def find_default_gateway(state: Dict[str, Any], iface: str) -> Optional[str]:
    """Return the IPv4 default gateway for iface.

    Do not use ``str(ipaddress.IPv4Network(0))`` here: Python renders that as
    ``0.0.0.0/32``, not the default route ``0.0.0.0/0``.  That subtle bug
    caused the shim to silently omit the gateway while preserving the address
    and DNS settings.
    """
    for route in (state.get("routes") or {}).get("config") or []:
        if not isinstance(route, dict):
            continue
        if route.get("next-hop-interface") != iface:
            continue
        destination = str(route.get("destination") or "").strip().lower()
        is_default = destination == "default"
        if not is_default:
            try:
                network = ipaddress.ip_network(destination, strict=False)
                is_default = network.version == 4 and network.prefixlen == 0
            except ValueError:
                is_default = False
        if is_default:
            gateway = route.get("next-hop-address")
            return str(gateway) if gateway is not None else None
    return None


def dns_servers(state: Dict[str, Any]) -> List[str]:
    servers = ((state.get("dns-resolver") or {}).get("config") or {}).get("server") or []
    return [str(s) for s in servers]


def validate_ip(ip: str) -> None:
    ipaddress.ip_address(str(ip))


def build_connection(state: Dict[str, Any], iface: Dict[str, Any]) -> List[str]:
    name = iface.get("name")
    if not name:
        raise ValueError("interface is missing name")

    iface_type = iface.get("type", "ethernet")
    if iface_type not in ("ethernet", "802-3-ethernet"):
        raise ValueError(
            f"agent shim only supports ethernet interfaces; interface {name} has type {iface_type}. "
            "Use a RHEL/Rocky bastion with the real nmstate package for bonds/VLANs/bridges."
        )

    mac = iface.get("mac-address") or iface.get("mac_address")
    ipv4 = iface.get("ipv4") or {}
    ipv6 = iface.get("ipv6") or {}
    gw = find_default_gateway(state, name)
    dns = dns_servers(state)

    conn_uuid = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"openshift-agent-{name}-{mac or ''}"))
    lines = [
        "[connection]",
        f"id={name}",
        f"uuid={conn_uuid}",
        "type=ethernet",
        f"interface-name={name}",
        "",
        "[ethernet]",
    ]
    if mac:
        lines.append(f"mac-address={mac}")
    lines.append("")

    lines.append("[ipv4]")
    if ipv4.get("enabled") is True:
        if ipv4.get("dhcp") is True:
            lines.append("method=auto")
        else:
            addresses = ipv4.get("address") or []
            if not addresses:
                raise ValueError(f"interface {name} has ipv4 enabled but no static address")
            first = addresses[0]
            ip = first.get("ip")
            prefix = first.get("prefix-length")
            if ip is None or prefix is None:
                raise ValueError(f"interface {name} static address requires ip and prefix-length")
            validate_ip(str(ip))
            prefix = int(prefix)
            if not 0 <= prefix <= 32:
                raise ValueError(f"interface {name} has invalid IPv4 prefix-length {prefix}")
            lines.append("method=manual")
            lines.append(f"address1={ip}/{prefix}")
            if gw:
                validate_ip(str(gw))
                lines.append(f"gateway={gw}")
                lines.append("never-default=false")
                lines.append("route-metric=100")
            if dns:
                for server in dns:
                    validate_ip(server)
                lines.append("dns=" + ";".join(dns) + ";")
            lines.append("may-fail=false")
    else:
        lines.append("method=disabled")
    lines.append("")

    lines.append("[ipv6]")
    if ipv6.get("enabled") is True:
        lines.append("method=auto" if ipv6.get("dhcp") is True or ipv6.get("autoconf") is True else "method=manual")
    else:
        lines.append("method=disabled")
    lines.append("")

    return [f"{name}.nmconnection", "\n".join(lines)]


def run_gc(args: List[str]) -> None:
    state = load_state(args)
    interfaces = state.get("interfaces") or []
    if not isinstance(interfaces, list) or not interfaces:
        raise ValueError("network state must contain a non-empty interfaces list")

    nm_connections: List[List[str]] = []
    for iface in interfaces:
        if not isinstance(iface, dict):
            raise ValueError("each interface must be an object")
        if iface.get("state", "up") == "absent":
            continue
        nm_connections.append(build_connection(state, iface))

    if not nm_connections:
        raise ValueError("no NetworkManager connections generated")

    sys.stdout.write(yaml.safe_dump({"NetworkManager": nm_connections}, sort_keys=False))


def main() -> int:
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help", "help"):
        usage()
        return 0
    if args[0] in ("--version", "version"):
        print(VERSION)
        return 0
    if args[0] in ("gc", "genconf", "generate-config"):
        try:
            run_gc(args)
            return 0
        except Exception as exc:
            print(f"agent-shim nmstatectl gc failed: {exc}", file=sys.stderr)
            return 1
    print(f"unsupported nmstatectl command: {' '.join(args)}", file=sys.stderr)
    usage()
    return 2


if __name__ == "__main__":
    sys.exit(main())
PY
chmod 0755 "${VENV_DIR}/bin/nmstatectl.agent-shim.py"

cat > "${VENV_DIR}/bin/nmstatectl" <<EOF2
#!/usr/bin/env bash
exec "${VENV_DIR}/bin/python" "${VENV_DIR}/bin/nmstatectl.agent-shim.py" "\$@"
EOF2
chmod 0755 "${VENV_DIR}/bin/nmstatectl"

hash -r
command -v nmstatectl
nmstatectl --version

# Self-test the exact default-route behavior that previously regressed.
selftest="$(mktemp)"
trap 'rm -f "${selftest}"' EXIT
cat > "${selftest}" <<'EOF_SELFTEST'
interfaces:
  - name: eth0
    type: ethernet
    state: up
    mac-address: 00:50:56:aa:bb:cc
    ipv4:
      enabled: true
      dhcp: false
      address:
        - ip: 192.0.2.10
          prefix-length: 24
    ipv6:
      enabled: false
routes:
  config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.0.2.1
      next-hop-interface: eth0
dns-resolver:
  config:
    server:
      - 192.0.2.53
EOF_SELFTEST
selftest_output="$(nmstatectl gc "${selftest}")"
if ! grep -q 'gateway=192.0.2.1' <<<"${selftest_output}"; then
  echo "ERROR: nmstatectl shim self-test failed: default gateway was dropped." >&2
  echo "${selftest_output}" >&2
  exit 1
fi
echo "nmstatectl default-route self-test passed (gateway=192.0.2.1)."

echo "nmstatectl shim installed successfully."
echo "Note: this shim is intended only for this repo's simple static ethernet Agent ISO config."
