---
- import_playbook: 08_apply_baremetal_cluster.yml
  vars:
    bm_cluster_name: "{{ site_b_cluster_name }}"
    bm_cluster_display_name: "{{ site_b_cluster_display_name }}"
    bm_base_domain: "{{ site_b_base_domain }}"
    bm_fqdn: "{{ site_b_fqdn }}"
    bm_clusterset: "{{ site_b_clusterset }}"
    bm_machine_cidr: "{{ site_b_machine_cidr }}"
    bm_machine_cidr_prefix: "{{ site_b_machine_cidr_prefix }}"
    bm_gateway: "{{ site_b_gateway }}"
    bm_dns_servers: "{{ site_b_dns_servers }}"
    bm_api_vip: "{{ site_b_api_vip }}"
    bm_ingress_vip: "{{ site_b_ingress_vip }}"
    bm_cluster_network_cidr: "{{ site_b_cluster_network_cidr }}"
    bm_cluster_network_host_prefix: "{{ site_b_cluster_network_host_prefix }}"
    bm_service_network_cidr: "{{ site_b_service_network_cidr }}"
    bm_network_type: "{{ site_b_network_type }}"
    bm_control_plane_count: "{{ site_b_control_plane_count }}"
    bm_worker_count: "{{ site_b_worker_count }}"
    bm_pull_secret_name: "{{ site_b_pull_secret_name }}"
    bm_nodes: "{{ site_b_nodes }}"
    bm_dns_records: "{{ site_b_dns_records }}"
    bm_rendered_dir: "{{ site_b_rendered_dir }}"
